server:
  port: 8761

spring:
  application:
    name: farmape-ms-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:${server.port}/eureka/}

info:
  app:
    name: FARMAPE Eureka Server
    description: Registro de servicios para los microservicios de FARMAPE.
