server:
  port: 8080

spring:
  application:
    name: farmape-ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

info:
  app:
    name: FARMAPE API Gateway
    description: Punto de entrada HTTP para el frontend de FARMAPE.
