server:
  port: 8081

spring:
  application:
    name: farmape-ms-inventario

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: FARMAPE Inventario
    description: Microservicio de productos, lotes y movimientos de almacen.
