server:
  port: 8888

spring:
  application:
    name: farmape-ms-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
        fail-on-composite-error: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: FARMAPE Config Server
    description: Servidor de configuracion centralizada para los microservicios de FARMAPE.
