apiVersion: v1
kind: Secret
metadata:
  labels:
    io.kompose.service: mysql-inventario
  name: mysql-inventario-secret
type: Opaque
stringData:
  MYSQL_DATABASE: farmape_inventario
  MYSQL_USER: farmape
  MYSQL_PASSWORD: farmape
  MYSQL_ROOT_PASSWORD: root
