server:
  port: 8761

spring:
  application:
    name: farmape-ms-eureka
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:${server.port}/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: FARMAPE Eureka Server
    description: Registro de servicios para los microservicios de FARMAPE.
